name: Run JMeter Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: tush-tr/setup-jmeter@v1.1.0 

      - name: Run JMeter tests
        run: jmeter -n -t ./JmeterTestFiles/TwitterV2.jmx -l ./JmeterTestFiles/results.jtl
