name: Run JMeter Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run JMeter Tests
        run: |
          jmeter -n -t JmeterTestFiles/TwitterV2.jmx -l JmeterTestFiles/results.jtl
