name: Test JMeter Action

on:
  push:
    branches: [main, dev]

jobs:
  action_build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Run JMeter Action on a test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: LoadTests/users_test.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"

      - uses: actions/upload-artifact@v1
        with:
          name: jmeter-test-results
          path: reports/
